### ISSUE TITLE
Consider support for promiseTypeDelimiter / promiseTypeSuffixes

### ISSUE THREAD

**Issue by tb** [omichelsen/redux-promise-middleware-actions#12]
redux-promise-middleware allows configuring promiseTypeDelimiter and promiseTypeSuffixes
See: https://docs.psb.design/redux-promise-middleware/guides/custom-delimiters

But redux-promise-middleware-actions has them hardcoded https://github.com/omichelsen/redux-promise-middleware-actions/blob/master/src/actions.ts#L1

**Comment by omichelsen** [comment]
I published v2.2.0 with support for this.
