### ISSUE TITLE
Question: how can I access dispatch() and getState() in my action payload creator?

### ISSUE THREAD

**Issue by sregg** [omichelsen/redux-promise-middleware-actions#20]
Just like we would with Redux Thunk.

P.S. I tried to add the `question` label but I couldn't find how.

**Comment by omichelsen** [comment]
This library just creates actions (objects) that hold a `Promise` as the payload. To use Redux Thunk you could for example do like this, similar to how you would normally do thunks:

```js
// create a normal async promise action
const myAsyncAction = createAsyncAction('ASYNC', (data) => Promise.resolve(data))

// create a thunk that gives it the arguments it needs from the state
const myThunkAction = () => (dispatch, getState) => {
  const state = getState()
  dispatch(myAsyncAction(state.data))
}

// dispatch like normal
dispatch(myThunkAction())
```

Does that help your use case?

**Comment by sregg** [comment]
Actually that works great!
I thought I tried something similar and had some TS error and gave up too quickly...
Thanks again for this great package!
